rpi_config:
  rpi_hostname: "192.168.8.102"
  rpi_DUT_path: "/home/ubuntu/Oct16_dut/connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-app"
  rpi_command: "./chip-all-clusters-app"
  rpi_user: "ubuntu"
  rpi_password: "raspberrypi"
general_configs:
  platform_execution: "rpi" #only two options supported "rpi" for raspberrypi and "CustomDUT" for user's DUT
  dut_connection_timeout: 60
  commissioning_metod: "on-network" # supported options "on-network", "ble-wifi, "ble-thread"
  iteration_number: 1000
  execution_mode_full: True
  dut_controller_file_path: "/home/ubuntu/Oct16_cntr/connectedhomeip/src/python_testing"
  logFilePath: null # when null value is set the script will create a folder called 'Iteration_logs' in current directory where logs will be stored.

