host: 0.0.0.0
port: 5000
workers: 1 # used for scaling
logs_path: /Users/chaitanyajandhyala/code/stressScripts/Functional/logs
python_environment: /Users/chaitanyajandhyala/code/chipCode/chip_0104/connectedhomeip/out/python_env
script_path: /Users/chaitanyajandhyala/code/chipCode/chip_0104/connectedhomeip/src/python_testing/Matter_QA/Scripts/ReliabilityScripts
